name: SWE-Bench Leaderboard Scraper

on:
  schedule:
    - cron: '0 * * * *' # 每小時執行一次
  workflow_dispatch: {} # 允許手動觸發

jobs:
  scrape-leaderboard:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: write # 需要寫入 action storage 的權限
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: |
          echo "today=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
          echo "timestamp=$(date +'%Y-%m-%d_%H-%M-%S')" >> "$GITHUB_OUTPUT"

      - name: Run Gemini Leaderboard Scraper
        uses: google-gemini/gemini-cli-action@main
        env:
          LEADERBOARD_URL: "https://swe-rebench.com/leaderboard"
          TODAY_DATE: ${{ steps.date.outputs.today }}
          TIMESTAMP: ${{ steps.date.outputs.timestamp }}
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          settings_json: |
            {
              "coreTools": [
                "run_shell_command(curl)",
                "run_shell_command(wget)",
                "run_shell_command(cat)",
                "run_shell_command(echo)",
                "run_shell_command(mkdir)",
                "run_shell_command(ls)"
              ]
            }
          prompt: |
            請從我提供的 leaderboard 爬取今日排行榜。

      - name: Upload leaderboard data to artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: swe-bench-leaderboard-${{ steps.date.outputs.timestamp }}
          path: |
            swe_bench_leaderboard_*.json
            leaderboard.html
          retention-days: 30

      - name: Cache latest leaderboard data
        uses: actions/cache/save@v4
        if: success()
        with:
          path: swe_bench_leaderboard_*.json
          key: swe-bench-leaderboard-latest-${{ steps.date.outputs.today }}