name: SWE-Bench Leaderboard Scraper

on:
  schedule:
    - cron: '0 * * * *' # 每小時執行一次
  workflow_dispatch: {} # 允許手動觸發

jobs:
  scrape-leaderboard:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: write # 需要寫入 action storage 的權限
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: |
          echo "today=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
          echo "timestamp=$(date +'%Y-%m-%d_%H-%M-%S')" >> "$GITHUB_OUTPUT"

      - name: Run Gemini Leaderboard Scraper
        uses: google-gemini/gemini-cli-action@main
        env:
          TODAY_DATE: ${{ steps.date.outputs.today }}
          TIMESTAMP: ${{ steps.date.outputs.timestamp }}
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          settings_json: |
            {
              "coreTools": [
                "WebFetchTool",
                "WriteFile"
              ]
            }
          prompt: |
            請從 https://swe-rebench.com/leaderboard 爬取今日排行榜資料，並將結果整理成 markdown 格式。
            
            要求：
            1. 爬取完整的排行榜資料，包含所有模型的排名、分數等資訊
            2. 將資料格式化為清晰易讀的 markdown 表格格式
            3. 在 markdown 開頭加上爬取時間和資料來源
            4. 將結果儲存為檔案，檔名格式：swe-bench-leaderboard.md
            
            請確保 markdown 檔案包含：
            - 標題和爬取時間
            - 資料來源連結
            - 完整的排行榜表格（包含排名、模型名稱、分數等欄位）
            - 任何重要的註解或說明

      - name: Upload leaderboard data to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: swe-bench-leaderboard-${{ steps.date.outputs.timestamp }}
          path: "*.md"
